spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID:}
            client-secret: ${AZURE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
              - offline_access
            redirect-uri: "http://localhost:8080/login/oauth2/code/azure"
            client-name: "Microsoft"
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:}/v2.0
  data:
    redis:
      host: ${REDIS_HOST}
      port: 18467
      username: default
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

superset:
  provider: db

datasources:
  primary:
    jdbc-url: ${PRIMARY_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${PRIMARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  secondary:
    jdbc-url: ${SECONDARY_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${SECONDARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  security:
    init-vector: ${INIT_VECTOR:}
    secret-key: ${SECRET_KEY:}
    jwt-secret-key: ${JWT_SECRET_KEY:}